"""
extract_features_sdxl_unclip.py
===============================
Exact replication of the original extract_features_sdxl_unclip.ipynb logic.

Extracts SDXL OpenCLIP (ViT-bigG-14) image embeddings from PNG images
previously generated by save_images.py.

Input:
  - Data/nsd/subj0{sub}/train_img/{i}.png    (425x425 RGB PNGs)
  - Data/nsd/subj0{sub}/test_img/{i}.png     (425x425 RGB PNGs)
  - checkpoints/sdxl_unclip/open_clip_pytorch_model.bin

Output (saved into Data/nsd/subj0{sub}/):
  - nsd_sdxl_clip_train_sub{sub}.npy          (N_train, 256, 1664)
  - nsd_sdxl_clip_pool_train_sub{sub}.npy     (N_train, 1664)
  - nsd_sdxl_clip_test_sub{sub}.npy           (N_test,  256, 1664)
  - nsd_sdxl_clip_pool_test_sub{sub}.npy      (N_test,  1664)

Usage:
  python SynBrain/data/extract_features_sdxl_unclip.py
"""

import sys
import os
import torch
import numpy as np
from PIL import Image
import torchvision.transforms.functional as TF
from torch.utils.data import DataLoader, Dataset

# ==============================================================================
# Configuration (paths relative to this script)
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '../../Data'))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, 'nsd')

# Model checkpoint path
OPEN_CLIP_MODEL_PATH = os.path.abspath(os.path.join(BASE_DIR, '../checkpoints/sdxl_unclip/open_clip_pytorch_model.bin'))

# Subjects to process (matching the original notebook)
SUBJECTS = [1, 2, 5, 7]

# Batch size (matching the original notebook)
BATCH_SIZE = 300

# ==============================================================================
# Import SGM modules
# ==============================================================================
# Original notebook: sys.path.append('.../SynBrain/src/sdxl/generative_models')
# Original notebook: from generative_models.sgm.modules.encoders.modules import FrozenOpenCLIPImageEmbedder
SGM_MODULE_PATH = os.path.abspath(os.path.join(SCRIPT_DIR, '../src/sdxl'))
sys.path.append(SGM_MODULE_PATH)

try:
    from generative_models.sgm.modules.encoders.modules import FrozenOpenCLIPImageEmbedder
except ImportError as e:
    print(f"Error importing SGM modules: {e}")
    print(f"Expected SGM path: {SGM_MODULE_PATH}/generative_models/sgm/modules/encoders/modules.py")
    sys.exit(1)

# ==============================================================================
# Check model file
# ==============================================================================
if not os.path.exists(OPEN_CLIP_MODEL_PATH):
    print(f"ERROR: open_clip_pytorch_model.bin not found at: {OPEN_CLIP_MODEL_PATH}")
    print("Please download from: https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/resolve/main/open_clip_pytorch_model.bin")
    sys.exit(1)

# ==============================================================================
# Initialize model (matching the original notebook exactly)
# ==============================================================================
# tf32 data type is faster than standard float32
torch.backends.cuda.matmul.allow_tf32 = True
device = 'cuda' if torch.cuda.is_available() else 'cpu'

clip_img_embedder = FrozenOpenCLIPImageEmbedder(
    arch="ViT-bigG-14",
    version=OPEN_CLIP_MODEL_PATH,
    output_tokens=True,
    only_tokens=False,
)
clip_img_embedder.to(device).eval()

clip_seq_dim = 256
clip_emb_dim = 1664

# ==============================================================================
# Dataset class (matching the original notebook exactly)
# ==============================================================================
class CLIP_Image_Dataset(Dataset):
    def __init__(self, image_path):
        self.img_data = image_path   # 图像path

    def __getitem__(self, idx):
        img = Image.open(self.img_data[idx])  # 一张图像对应1个fmri
        img = TF.to_tensor(img).float()
        return img

    def __len__(self):
        return len(self.img_data)

# ==============================================================================
# Extract features (matching the original notebook loop exactly)
# ==============================================================================
for subj in SUBJECTS:
    save_path = os.path.join(PROCESSED_DATA_DIR, f'subj0{subj}')
    if not os.path.exists(save_path):
        print(f"Subject {subj} folder not found at {save_path}, skipping...")
        continue

    print(f"\nProcessing Subject {subj}...")

    for mode in ['train', 'test']:
        image_dir = os.path.join(save_path, f'{mode}_img')
        if not os.path.exists(image_dir):
            print(f"  {mode}_img not found, skipping...")
            continue

        # Build sorted file list: 0.png, 1.png, 2.png, ...
        num_images = len([f for f in os.listdir(image_dir) if f.endswith('.png')])
        image_paths = np.array([os.path.join(image_dir, f'{i}.png') for i in range(num_images)])
        print(f'  {mode.capitalize()} images: {image_paths.shape}')

        dataset = CLIP_Image_Dataset(image_paths)
        dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, drop_last=False)

        zs = None
        zs_pool = None

        for batch_i, image in enumerate(dataloader):
            print(f"  Extracting Batch {batch_i} / {mode}...")

            with torch.no_grad():
                z, z_pool = clip_img_embedder(image.to(device))

            if batch_i == 0:
                zs = z.detach().cpu()
                zs_pool = z_pool.detach().cpu()
            else:
                zs = torch.cat((zs, z.detach().cpu()), dim=0)
                zs_pool = torch.cat((zs_pool, z_pool.detach().cpu()), dim=0)

            torch.cuda.empty_cache()

        if zs is not None:
            out_clip = os.path.join(save_path, f'nsd_sdxl_clip_{mode}_sub{subj}.npy')
            out_pool = os.path.join(save_path, f'nsd_sdxl_clip_pool_{mode}_sub{subj}.npy')
            np.save(out_clip, zs.numpy())
            np.save(out_pool, zs_pool.numpy())
            print(f"  Saved: {out_clip} shape={zs.shape}")
            print(f"  Saved: {out_pool} shape={zs_pool.shape}")
            del zs, zs_pool

print("\nDone. Feature extraction completed successfully!")
