"""
extract_features_dinov2.py
==========================
Extracts DINOv2 ViT-L/14 image features from PNG images
previously generated by save_images.py.

DINOv2 ViT-L/14 specs:
    - Embedding dim: 1024
    - Patch size: 14
    - Input: 224x224 → 16x16 = 256 patch tokens + 1 CLS token = 257 tokens
    - Output: (N, 257, 1024)

Input:
  - Data/nsd/subj0{sub}/train_img/{i}.png    (425x425 RGB PNGs)
  - Data/nsd/subj0{sub}/test_img/{i}.png     (425x425 RGB PNGs)

Output (saved into Data/nsd/subj0{sub}/):
  - nsd_dinov2_vitl14_train_sub{sub}.npy     (N_train, 257, 1024)  float16
  - nsd_dinov2_vitl14_test_sub{sub}.npy      (N_test,  257, 1024)  float16

Usage:
  python SynBrain/data/extract_features_dinov2.py
  python SynBrain/data/extract_features_dinov2.py --subjects 1
  python SynBrain/data/extract_features_dinov2.py --subjects 1 2 5 7 --batch_size 128
"""

import argparse
import os
import numpy as np
import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms

# ==============================================================================
# Configuration (paths relative to this script)
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '../../Data'))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, 'nsd')

# Default subjects (matching the CLIP extraction script)
DEFAULT_SUBJECTS = [1, 2, 5, 7]

# Default batch size
DEFAULT_BATCH_SIZE = 128

# DINOv2 ViT-L/14 constants
DINOV2_EMB_DIM = 1024
DINOV2_INPUT_SIZE = 224

# ImageNet normalization (required by DINOv2)
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)


# ==============================================================================
# Dataset class (same data mapping logic as CLIP extraction script)
# ==============================================================================
class DINOv2_Image_Dataset(Dataset):
    """
    Dataset that loads PNG images and applies DINOv2 preprocessing.
    Image paths are indexed 0..N-1 matching the fMRI data 1-to-1.
    """
    def __init__(self, image_paths, transform):
        self.img_data = image_paths
        self.transform = transform

    def __getitem__(self, idx):
        img = Image.open(self.img_data[idx]).convert('RGB')
        img = self.transform(img)
        return img

    def __len__(self):
        return len(self.img_data)


# ==============================================================================
# Main extraction logic
# ==============================================================================
def parse_args():
    parser = argparse.ArgumentParser(description="Extract DINOv2 ViT-L/14 features")
    parser.add_argument('--subjects', type=int, nargs='+', default=DEFAULT_SUBJECTS,
                        help='Subject numbers to process (default: 1 2 5 7)')
    parser.add_argument('--batch_size', type=int, default=DEFAULT_BATCH_SIZE,
                        help=f'Batch size (default: {DEFAULT_BATCH_SIZE})')
    parser.add_argument('--device', type=str, default='',
                        help='Device (default: auto-detect)')
    return parser.parse_args()


def main():
    args = parse_args()

    # ── Device ──
    device = args.device if args.device else ('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")

    # ── tf32 for faster computation ──
    torch.backends.cuda.matmul.allow_tf32 = True

    # ── Load DINOv2 ViT-L/14 from torch.hub ──
    print("Loading DINOv2 ViT-L/14 from torch.hub...")
    model = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitl14')
    model = model.to(device).eval()
    print(f"DINOv2 ViT-L/14 loaded. Embedding dim: {DINOV2_EMB_DIM}")

    # ── Preprocessing (DINOv2 standard) ──
    transform = transforms.Compose([
        transforms.Resize(DINOV2_INPUT_SIZE, interpolation=transforms.InterpolationMode.BICUBIC),
        transforms.CenterCrop(DINOV2_INPUT_SIZE),
        transforms.ToTensor(),
        transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])

    # ── Extract features per subject ──
    for subj in args.subjects:
        save_path = os.path.join(PROCESSED_DATA_DIR, f'subj0{subj}')
        if not os.path.exists(save_path):
            print(f"\nSubject {subj} folder not found at {save_path}, skipping...")
            continue

        print(f"\n{'='*60}")
        print(f"Processing Subject {subj}...")
        print(f"{'='*60}")

        for mode in ['train', 'test']:
            image_dir = os.path.join(save_path, f'{mode}_img')
            if not os.path.exists(image_dir):
                print(f"  {mode}_img not found, skipping...")
                continue

            # Build sorted file list: 0.png, 1.png, 2.png, ...
            # Same logic as CLIP extraction — ensures 1-to-1 mapping with fMRI data
            num_images = len([f for f in os.listdir(image_dir) if f.endswith('.png')])
            image_paths = np.array([
                os.path.join(image_dir, f'{i}.png') for i in range(num_images)
            ])
            print(f'  {mode.capitalize()} images: {num_images}')

            dataset = DINOv2_Image_Dataset(image_paths, transform)
            dataloader = DataLoader(
                dataset, batch_size=args.batch_size,
                drop_last=False, num_workers=4, pin_memory=True,
            )

            all_features = []

            for batch_i, images in enumerate(dataloader):
                if batch_i % 10 == 0:
                    print(f"  Extracting Batch {batch_i}/{len(dataloader)} / {mode}...")

                with torch.no_grad(), torch.amp.autocast('cuda', enabled=(device == 'cuda')):
                    # DINOv2 forward_features returns dict with:
                    #   'x_norm_clstoken': (B, D)
                    #   'x_norm_patchtokens': (B, N_patches, D)
                    output = model.forward_features(images.to(device))

                    cls_token = output['x_norm_clstoken']        # (B, 1024)
                    patch_tokens = output['x_norm_patchtokens']  # (B, 256, 1024)

                    # Concatenate: [CLS, patch_1, patch_2, ..., patch_256] → (B, 257, 1024)
                    features = torch.cat([
                        cls_token.unsqueeze(1),  # (B, 1, 1024)
                        patch_tokens,            # (B, 256, 1024)
                    ], dim=1)

                all_features.append(features.cpu().half())  # fp16 to save space
                torch.cuda.empty_cache()

            if all_features:
                all_features = torch.cat(all_features, dim=0).numpy()  # (N, 257, 1024), float16

                out_path = os.path.join(
                    save_path, f'nsd_dinov2_vitl14_{mode}_sub{subj}.npy'
                )
                np.save(out_path, all_features)
                print(f"  ✅ Saved: {out_path}")
                print(f"     Shape: {all_features.shape}, Dtype: {all_features.dtype}")
                print(f"     Size: {all_features.nbytes / 1e6:.1f} MB")
                del all_features

    print(f"\n{'='*60}")
    print("Done. DINOv2 feature extraction completed successfully!")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
